// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessZero.Domain;

#nullable disable

namespace ProcessZero.Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721_CreateCreditSystem")]
    partial class CreateCreditSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProcessZero.Domain.Entities.CreditPackage", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<decimal>("CreditAmount")
                    .HasColumnType("decimal(65,30)");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("varchar(3)");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.Property<int?>("DurationMinutes")
                    .HasColumnType("int");

                b.Property<bool>("IsActive")
                    .HasColumnType("tinyint(1)");

                b.Property<bool>("IsSubscription")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(65,30)");

                b.Property<decimal?>("DiscountPercentage")
                    .HasColumnType("decimal(65,30)");

                b.Property<int>("SortOrder")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<string>("UserId")
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.HasIndex("IsActive")
                    .HasDatabaseName("IX_CreditPackages_IsActive");

                b.HasIndex("SortOrder")
                    .HasDatabaseName("IX_CreditPackages_SortOrder");

                b.ToTable("CreditPackages");
            });

            modelBuilder.Entity("ProcessZero.Domain.Entities.UserWallet", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<decimal>("CreditBalance")
                    .HasColumnType("decimal(65,30)");

                b.Property<DateTime?>("LastUpdatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<string>("SubscriptionId")
                    .HasMaxLength(256)
                    .HasColumnType("varchar(256)");

                b.Property<string>("SubscriptionStatus")
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)");

                b.Property<decimal>("TotalCreditsConsumed")
                    .HasColumnType("decimal(65,30)");

                b.Property<decimal>("TotalCreditsPurchased")
                    .HasColumnType("decimal(65,30)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(450)
                    .HasColumnType("varchar(450)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime(6)");

                b.HasKey("Id");

                b.HasIndex("UserId")
                    .IsUnique()
                    .HasDatabaseName("IX_UserWallets_UserId");

                b.ToTable("UserWallets");

                b.HasOne("ProcessZero.Domain.ApplicationUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("ProcessZero.Domain.Entities.CreditTransaction", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<decimal>("BalanceAfterTransaction")
                    .HasColumnType("decimal(65,30)");

                b.Property<decimal>("CreditAmount")
                    .HasColumnType("decimal(65,30)");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.Property<int?>("RelatedEntityId")
                    .HasColumnType("int");

                b.Property<string>("RelatedEntityType")
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<string>("ReferenceId")
                    .HasMaxLength(256)
                    .HasColumnType("varchar(256)");

                b.Property<int>("TransactionType")
                    .HasColumnType("int");

                b.Property<int>("UserWalletId")
                    .HasColumnType("int");

                b.Property<DateTime>("TransactionDate")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime(6)");

                b.HasKey("Id");

                b.HasIndex("UserWalletId")
                    .HasDatabaseName("IX_CreditTransactions_UserWalletId");

                b.HasIndex("TransactionDate")
                    .HasDatabaseName("IX_CreditTransactions_TransactionDate");

                b.HasIndex("UserWalletId", "TransactionDate")
                    .HasDatabaseName("IX_CreditTransactions_UserWalletId_TransactionDate");

                b.ToTable("CreditTransactions");

                b.HasOne("ProcessZero.Domain.Entities.UserWallet", "UserWallet")
                    .WithMany()
                    .HasForeignKey("UserWalletId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}